#:schema node_modules/wrangler/config-schema.json
name = "sandbox-remix-cloudflare"
compatibility_date = "2024-11-12"
main = "./server.ts"
assets = { directory = "./build/client" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "sandbox-remix-cloudflare"
database_id = "eefc8f66-db64-4c76-8bd1-826fffb11de5"
migrations_dir = "./migrations"
